//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecretSanta.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users that could not be matched.
        /// </summary>
        public static string AbandonedUsers {
            get {
                return ResourceManager.GetString("AbandonedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Account.
        /// </summary>
        public static string AccountRemove {
            get {
                return ResourceManager.GetString("AccountRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete your account. This action cannot be reversed and you will have to register again. Are you sure?.
        /// </summary>
        public static string AccountRemoveIntro {
            get {
                return ResourceManager.GetString("AccountRemoveIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1 is required for postal purposes.
        /// </summary>
        public static string AddressLine1_Required {
            get {
                return ResourceManager.GetString("AddressLine1_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1 is limited to 200 characters.
        /// </summary>
        public static string AddressLine1_TooLong {
            get {
                return ResourceManager.GetString("AddressLine1_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2 is limited to 200 characters.
        /// </summary>
        public static string AddressLine2_TooLong {
            get {
                return ResourceManager.GetString("AddressLine2_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been approved by an admin..
        /// </summary>
        public static string Admin_Confirmed {
            get {
                return ResourceManager.GetString("Admin_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has not been yet approved by an admin..
        /// </summary>
        public static string Admin_NotConfirmed {
            get {
                return ResourceManager.GetString("Admin_NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators.
        /// </summary>
        public static string AdminIndex {
            get {
                return ResourceManager.GetString("AdminIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting confirmations.
        /// </summary>
        public static string AdminUnconfirmed {
            get {
                return ResourceManager.GetString("AdminUnconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Users.
        /// </summary>
        public static string AdminUser {
            get {
                return ResourceManager.GetString("AdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin User Name.
        /// </summary>
        public static string AdminUserName {
            get {
                return ResourceManager.GetString("AdminUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name for admin account must be alphanumerical (no whitespace or special characters).
        /// </summary>
        public static string AdminUserName_Invalid {
            get {
                return ResourceManager.GetString("AdminUserName_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name for admin account is required.
        /// </summary>
        public static string AdminUserName_Required {
            get {
                return ResourceManager.GetString("AdminUserName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name for admin account is limited to 200 characters.
        /// </summary>
        public static string AdminUserName_TooLong {
            get {
                return ResourceManager.GetString("AdminUserName_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are all done - now wait for the assignment of the recepient of your gift..
        /// </summary>
        public static string AllReady {
            get {
                return ResourceManager.GetString("AllReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users were matched!.
        /// </summary>
        public static string AllUsersMatched {
            get {
                return ResourceManager.GetString("AllUsersMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign recepients.
        /// </summary>
        public static string Assignment {
            get {
                return ResourceManager.GetString("Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment completed.
        /// </summary>
        public static string AssignmentCompleted {
            get {
                return ResourceManager.GetString("AssignmentCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assignment has been already done..
        /// </summary>
        public static string AssignmentDone {
            get {
                return ResourceManager.GetString("AssignmentDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City (or town, village etc.) is required for postal purposes.
        /// </summary>
        public static string City_Required {
            get {
                return ResourceManager.GetString("City_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is limited to 200 characters.
        /// </summary>
        public static string City_TooLong {
            get {
                return ResourceManager.GetString("City_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close registration.
        /// </summary>
        public static string CloseRegistration {
            get {
                return ResourceManager.GetString("CloseRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration succesful. Email with a confirmation link was sent to.
        /// </summary>
        public static string ConfirmationEmailSent {
            get {
                return ResourceManager.GetString("ConfirmationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand and accept usage of cookies.
        /// </summary>
        public static string CookieBanner_Accept {
            get {
                return ResourceManager.GetString("CookieBanner_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The law requires to inform users about usage of cookies, which is just as universal as the internet itself. Click that you understand and accept. Also, The EU should be destroyed..
        /// </summary>
        public static string CookieBanner_Message {
            get {
                return ResourceManager.GetString("CookieBanner_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required for postal purposes.
        /// </summary>
        public static string Country_Required {
            get {
                return ResourceManager.GetString("Country_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is limited to 200 characters.
        /// </summary>
        public static string Country_TooLong {
            get {
                return ResourceManager.GetString("Country_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create admin account.
        /// </summary>
        public static string CreateAdmin {
            get {
                return ResourceManager.GetString("CreateAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display name is required.
        /// </summary>
        public static string DisplayName_Required {
            get {
                return ResourceManager.GetString("DisplayName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display name is limited to 200 characters.
        /// </summary>
        public static string DisplayName_TooLong {
            get {
                return ResourceManager.GetString("DisplayName_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit admin.
        /// </summary>
        public static string EditAdmin {
            get {
                return ResourceManager.GetString("EditAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has been confirmed..
        /// </summary>
        public static string Email_Confirmed {
            get {
                return ResourceManager.GetString("Email_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid email address.
        /// </summary>
        public static string Email_HelpText {
            get {
                return ResourceManager.GetString("Email_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is invalid.
        /// </summary>
        public static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address has not been yet confirmed..
        /// </summary>
        public static string Email_NotConfirmed {
            get {
                return ResourceManager.GetString("Email_NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}! Click on following link to go to your password reset form. If you have not requested a password reset, you can safely delete this email. The token will be valid for {2} minutes. {1}.
        /// </summary>
        public static string Email_PasswordReset_Body {
            get {
                return ResourceManager.GetString("Email_PasswordReset_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Santa Password Reset.
        /// </summary>
        public static string Email_PasswordReset_Subject {
            get {
                return ResourceManager.GetString("Email_PasswordReset_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required to send the confirmation and details of a person chosen for you.
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend confirmation email.
        /// </summary>
        public static string Email_ResendConfirmatioon {
            get {
                return ResourceManager.GetString("Email_ResendConfirmatioon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to send an email. Please wait 15 minutes and try again, and if you see this message again contact an administrator..
        /// </summary>
        public static string Email_SendingFailure {
            get {
                return ResourceManager.GetString("Email_SendingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}! To complete your registration please open following link in your browser: {1}.
        /// </summary>
        public static string Email_Verification_Body {
            get {
                return ResourceManager.GetString("Email_Verification_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Santa account creation confirmation.
        /// </summary>
        public static string Email_Verification_Subject {
            get {
                return ResourceManager.GetString("Email_Verification_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation token is invalid..
        /// </summary>
        public static string EmailConfirmation_TokenInvalid {
            get {
                return ResourceManager.GetString("EmailConfirmation_TokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has been confirmed..
        /// </summary>
        public static string EmailConfirmedMessage {
            get {
                return ResourceManager.GetString("EmailConfirmedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has been already registered.
        /// </summary>
        public static string EmailTaken {
            get {
                return ResourceManager.GetString("EmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to the Facebook profile.
        /// </summary>
        public static string FacebookURL {
            get {
                return ResourceManager.GetString("FacebookURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid URL to your Facebook profile (including http:// or https://).
        /// </summary>
        public static string FacebookURL_HelpText {
            get {
                return ResourceManager.GetString("FacebookURL_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL is invalid.
        /// </summary>
        public static string FacebookURL_Invalid {
            get {
                return ResourceManager.GetString("FacebookURL_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to the Facebook profile is required for verification.
        /// </summary>
        public static string FacebookURL_Required {
            get {
                return ResourceManager.GetString("FacebookURL_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your full name is required for postal purposes.
        /// </summary>
        public static string FullName_Required {
            get {
                return ResourceManager.GetString("FullName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full name is limited to 200 characters.
        /// </summary>
        public static string FullName_TooLong {
            get {
                return ResourceManager.GetString("FullName_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giver.
        /// </summary>
        public static string Giver {
            get {
                return ResourceManager.GetString("Giver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string InitialSetup {
            get {
                return ResourceManager.GetString("InitialSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec convallis nisl nec molestie suscipit. Pellentesque finibus pretium iaculis. Mauris tempus dui at odio feugiat, non hendrerit lorem tincidunt. Aenean id tincidunt ex. Suspendisse gravida ornare turpis sit amet ultricies. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pellentesque nisi nec tempus vestibulum. Vestibulum ipsum enim, cursus vitae eros ac, ullamcorper sodales purus. Donec eget nisl pellentesque, eleifend lectus quis,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or password invalid.
        /// </summary>
        public static string Login_Invalid {
            get {
                return ResourceManager.GetString("Login_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is locked.
        /// </summary>
        public static string Login_LockedOut {
            get {
                return ResourceManager.GetString("Login_LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or admin login.
        /// </summary>
        public static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you forgotten your password?.
        /// </summary>
        public static string Menu_ForgotPassword {
            get {
                return ResourceManager.GetString("Menu_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assignment has been already done - you cannot remove your account!.
        /// </summary>
        public static string Message_CannotRemoveAccountAfterAssignment {
            get {
                return ResourceManager.GetString("Message_CannotRemoveAccountAfterAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation link was sent to your email address..
        /// </summary>
        public static string Message_ResendConfirmation {
            get {
                return ResourceManager.GetString("Message_ResendConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users require confirmation!.
        /// </summary>
        public static string NothingToConfirm {
            get {
                return ResourceManager.GetString("NothingToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one has yet registered.
        /// </summary>
        public static string NoUsers {
            get {
                return ResourceManager.GetString("NoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open registration.
        /// </summary>
        public static string OpenRegistration {
            get {
                return ResourceManager.GetString("OpenRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be minimum 8 characters long, three characters of (lowercase letter, uppercase letter, digit, special character) and cannot be a common pattern. See &lt;a tabindex=&quot;-1&quot; href=&quot;https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Password_Complexity&quot;&gt;OWASP recommendation&lt;/a&gt; for details..
        /// </summary>
        public static string Password_HelpText {
            get {
                return ResourceManager.GetString("Password_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet the complexity requirements..
        /// </summary>
        public static string Password_Invalid {
            get {
                return ResourceManager.GetString("Password_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password confirmation does not equal password..
        /// </summary>
        public static string PasswordConfirmation_NoMatch {
            get {
                return ResourceManager.GetString("PasswordConfirmation_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there is an account registered with provided email address, an email with password reset link was sent to it..
        /// </summary>
        public static string PasswordReset_Sent {
            get {
                return ResourceManager.GetString("PasswordReset_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset succesfully.
        /// </summary>
        public static string PasswordReset_Success {
            get {
                return ResourceManager.GetString("PasswordReset_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string PasswordReset_Title {
            get {
                return ResourceManager.GetString("PasswordReset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset token.
        /// </summary>
        public static string PasswordReset_Token_Display {
            get {
                return ResourceManager.GetString("PasswordReset_Token_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset token is invalid or has expired..
        /// </summary>
        public static string PasswordReset_TokenInvalid {
            get {
                return ResourceManager.GetString("PasswordReset_TokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code is required for postal purposes.
        /// </summary>
        public static string PostalCode_Required {
            get {
                return ResourceManager.GetString("PostalCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code is limited to 32 characters.
        /// </summary>
        public static string PostalCode_TooLong {
            get {
                return ResourceManager.GetString("PostalCode_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been assigned a recepient! Check the information below and send your gift as soon as you can!.
        /// </summary>
        public static string RecepientAssigned {
            get {
                return ResourceManager.GetString("RecepientAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipient also left a note:.
        /// </summary>
        public static string RecepientLeftNote {
            get {
                return ResourceManager.GetString("RecepientLeftNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields with asterisk (*) are required..
        /// </summary>
        public static string Registration_FieldsWithAsterisk {
            get {
                return ResourceManager.GetString("Registration_FieldsWithAsterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree.
        /// </summary>
        public static string Registration_Form_Agreement {
            get {
                return ResourceManager.GetString("Registration_Form_Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to the privacy policy..
        /// </summary>
        public static string Registration_Form_Agreement_Error {
            get {
                return ResourceManager.GetString("Registration_Form_Agreement_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand and agree to the {0}.
        /// </summary>
        public static string Registration_Form_Agreement_HelpText {
            get {
                return ResourceManager.GetString("Registration_Form_Agreement_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registrations has been closed..
        /// </summary>
        public static string RegistrationClosed {
            get {
                return ResourceManager.GetString("RegistrationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is registration open?.
        /// </summary>
        public static string RegistrationOpen {
            get {
                return ResourceManager.GetString("RegistrationOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove User.
        /// </summary>
        public static string RemoveUser {
            get {
                return ResourceManager.GetString("RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to remove the following user. This action cannot be reversed and the user will have to register again..
        /// </summary>
        public static string RemoveUserIntro {
            get {
                return ResourceManager.GetString("RemoveUserIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to send gift abroad (be aware of potential costs, which might be very high!).
        /// </summary>
        public static string SentAbroad {
            get {
                return ResourceManager.GetString("SentAbroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Name.
        /// </summary>
        public static string SettingName {
            get {
                return ResourceManager.GetString("SettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Value.
        /// </summary>
        public static string SettingValue {
            get {
                return ResourceManager.GetString("SettingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Santa.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string SystemMessage {
            get {
                return ResourceManager.GetString("SystemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update succesful. Because you have changed your email, a confirmation link has been sent to provided address: {0}. You must also sign-in again!.
        /// </summary>
        public static string User_Edit_EmailSent {
            get {
                return ResourceManager.GetString("User_Edit_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        public static string User_Edit_Title {
            get {
                return ResourceManager.GetString("User_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, changing your data will revoke the admin confirmation of your account. Also, changing your email address will revoke the email confirmation!.
        /// </summary>
        public static string User_Edit_Warning {
            get {
                return ResourceManager.GetString("User_Edit_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed by admin.
        /// </summary>
        public static string User_View_AdminConfirmed {
            get {
                return ResourceManager.GetString("User_View_AdminConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account.
        /// </summary>
        public static string User_View_Edit {
            get {
                return ResourceManager.GetString("User_View_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmed.
        /// </summary>
        public static string User_View_EmailConfirmed {
            get {
                return ResourceManager.GetString("User_View_EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! The app is runing in test mode. All data will be purged before full launch..
        /// </summary>
        public static string Warning_TestMode {
            get {
                return ResourceManager.GetString("Warning_TestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will Send Abroad.
        /// </summary>
        public static string WillSendAbroad {
            get {
                return ResourceManager.GetString("WillSendAbroad", resourceCulture);
            }
        }
    }
}
